---
# This Ansible playbook, checks if a directory exists at /local/test, and if it exists, it assigns user/group permission as defined below
- hosts: all
  tasks:
  - name: check for directory
    stat:
      path: /local/test
    register: dir_status
  - name: Set owner and Group
    file:
      path: /local/test
      owner: cassandra
      group: cassandra
      state: directory
    when: dir_status.stat.isdir is defined and dir_status.stat.isdir
